INSERT INTO NEW_PACKAGES (ID, PROVISIONING_PACKAGES_ID, PACKAGE_NAME, CREATED_AT, MODIFIED_AT, PACKAGE_COST, REFILL_ID, TRANS_AMOUNT)
VALUES ('22','22', 'MyMeg 50(GIFT)', sysdate, sysdate, '1000','MB20','1000')
/

INSERT INTO NEW_PACKAGES (ID, PROVISIONING_PACKAGES_ID, PACKAGE_NAME, CREATED_AT, MODIFIED_AT, PACKAGE_COST, REFILL_ID, TRANS_AMOUNT)
VALUES ('23','23', 'MyMeg 100(GIFT)', sysdate, sysdate, '3000','MB22','3000')
/

INSERT INTO NEW_PACKAGES (ID, PROVISIONING_PACKAGES_ID, PACKAGE_NAME, CREATED_AT, MODIFIED_AT, PACKAGE_COST, REFILL_ID, TRANS_AMOUNT)
VALUES ('24','24', 'MyMeg 250(GIFT)', sysdate, sysdate, '13500','MB24','135000')
/

INSERT INTO NEW_PACKAGES (ID, PROVISIONING_PACKAGES_ID, PACKAGE_NAME, CREATED_AT, MODIFIED_AT, PACKAGE_COST, REFILL_ID, TRANS_AMOUNT)
VALUES ('25','25', 'MyMeg 500(GIFT)', sysdate, sysdate, '25500','MB25','25500')
/

INSERT INTO NEW_PACKAGES (ID, PROVISIONING_PACKAGES_ID, PACKAGE_NAME, CREATED_AT, MODIFIED_AT, PACKAGE_COST, REFILL_ID, TRANS_AMOUNT)
VALUES ('26','26', 'MyGig 1(GIFT)', sysdate, sysdate, '45000','MB27','45000')
/

INSERT INTO NEW_PACKAGES (ID, PROVISIONING_PACKAGES_ID, PACKAGE_NAME, CREATED_AT, MODIFIED_AT, PACKAGE_COST, REFILL_ID, TRANS_AMOUNT)
VALUES ('27','27', 'MyGig 2GIFT)', sysdate, sysdate, '67500','MB28','67500')
/

INSERT INTO NEW_PACKAGES (ID, PROVISIONING_PACKAGES_ID, PACKAGE_NAME, CREATED_AT, MODIFIED_AT, PACKAGE_COST, REFILL_ID, TRANS_AMOUNT)
VALUES ('28','28', 'MyGig 5(GIFT)', sysdate, sysdate, '90000','MB30','90000')
/

INSERT INTO NEW_PACKAGES (ID, PROVISIONING_PACKAGES_ID, PACKAGE_NAME, CREATED_AT, MODIFIED_AT, PACKAGE_COST, REFILL_ID, TRANS_AMOUNT)
VALUES ('29','29', 'MyGig 10(GIFT)', sysdate, sysdate, '135000','MB31','135000')
/

INSERT INTO NEW_PACKAGES (ID, PROVISIONING_PACKAGES_ID, PACKAGE_NAME, CREATED_AT, MODIFIED_AT, PACKAGE_COST, REFILL_ID, TRANS_AMOUNT)
VALUES ('30','30', 'MyGig 30(GIFT)', sysdate, sysdate, '180000','MB32','180000')
/




INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('22', '1','50', '1', '1030')
/

INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('23', '1','100', '1', '1032')
/

INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('24', '1','250', '7', '1034')
/

INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('25', '1','500', '7', '1035')
/

INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('26', '1','1024', '30', '1037')
/

INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('27', '1','2048', '30', '1038')
/

INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('28', '1','5120', '30', '1040')
/

INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('29', '1','10240', '30', '1041')
/

INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('30', '1','30720', '30', '1042')
/

