CREATE TABLE MEG_FIFTN_CDR
(
ID NUMBER(20),
MSISDN VARCHAR2(15),
B_MSISDN VARCHAR2(15),
ACTION VARCHAR2(15),
CREATED_AT TIMESTAMP,
MODIFIED_AT TIMESTAMP,
TRANSACTION_ID NUMBER(20),
STATUS_CODE NUMBER(5),
CONSTRAINT MEGFIFTN_CDR_PK PRIMARY KEY (ID)
)
/

CREATE SEQUENCE MEGFIFTN_CDR_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE CACHE 20 NOCYCLE;
/

CREATE OR REPLACE TRIGGER MEGFIFTN_CDR_TRG BEFORE INSERT ON MEG_FIFTN_CDR
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT MEGFIFTN_CDR_SEQ .NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER MEGFIFTN_CDR_TRG  ENABLE;





