CREATE TABLE MEG_FIFTN_TRACKER
   (    ID NUMBER NOT NULL,
        MSISDN VARCHAR2(20) NOT NULL,
        MORNING_COUNT NUMBER(5),
        AFTERNOON_COUNT NUMBER(5),
        REQUESTED_AT TIMESTAMP,
        COMPLETED_AT TIMESTAMP,
        SUCCESS NUMBER(10),
        CONSTRAINT MEGFIFTN_TRACKER_PK PRIMARY KEY (ID),
        CONSTRAINT MEGFIFTN_UK1 UNIQUE (MSISDN));


CREATE INDEX MEG_FIFTN_TRCK_INDEX ON MEG_FIFTN_TRACKER (COMPLETED_AT);
/

CREATE SEQUENCE MEG_FIFTN_TRACKER_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE CACHE 20 NOCYCLE
/

CREATE OR REPLACE TRIGGER MEG_FIFTN_TRACKER_TRG BEFORE INSERT ON MEG_FIFTN_TRACKER
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT MEG_FIFTN_TRACKER_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER MEG_FIFTN_TRACKER_TRG ENABLE;
/
