INSERT INTO NEW_PACKAGES (ID, PROVISIONING_PACKAGES_ID, PACKAGE_NAME, CREATED_AT, MODIFIED_AT, PACKAGE_COST, REFILL_ID, TRANS_AMOUNT)
VALUES ('31','31', 'MyMeg 10(NIGHT)', sysdate, sysdate, '600','MB33','600')
/

INSERT INTO NEW_PACKAGES (ID, PROVISIONING_PACKAGES_ID, PACKAGE_NAME, CREATED_AT, MODIFIED_AT, PACKAGE_COST, REFILL_ID, TRANS_AMOUNT)
VALUES ('32','32', 'MyMeg 20(NIGHT)', sysdate, sysdate, '980','MB34','980')
/

INSERT INTO NEW_PACKAGES (ID, PROVISIONING_PACKAGES_ID, PACKAGE_NAME, CREATED_AT, MODIFIED_AT, PACKAGE_COST, REFILL_ID, TRANS_AMOUNT)
VALUES ('33','33', 'MyMeg 50(NIGHT)', sysdate, sysdate, '1400','MB35','1400')
/

INSERT INTO NEW_PACKAGES (ID, PROVISIONING_PACKAGES_ID, PACKAGE_NAME, CREATED_AT, MODIFIED_AT, PACKAGE_COST, REFILL_ID, TRANS_AMOUNT)
VALUES ('34','34', 'MyMeg 60(NIGHT)', sysdate, sysdate, '1900','MB36','1900')
/

INSERT INTO NEW_PACKAGES (ID, PROVISIONING_PACKAGES_ID, PACKAGE_NAME, CREATED_AT, MODIFIED_AT, PACKAGE_COST, REFILL_ID, TRANS_AMOUNT)
VALUES ('35','35', 'MyMeg 100(NIGHT)', sysdate, sysdate, '2600','MB37','260')
/





INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('31', '2','50', '2', '1043')
/

INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('32', '2','100', '2', '1044')
/

INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('33', '5','250', '5', '1045')
/

INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('34', '7','500', '7', '1046')
/

INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('35', '7','1024', '7', '1047')
/
