CREATE TABLE NEW_PROVISIONING_PACKAGES
   ( ID NUMBER(11,0) NOT NULL ENABLE,
    PACKAGE_CATEGORY_ID NUMBER(11,0),
    CREATED_AT DATE,
    ACTIVE VARCHAR2(20),
    MODIFIED_AT DATE,
    VOLUME VARCHAR2(20),
    VALIDITY VARCHAR2(20),
    OFFER_ID VARCHAR(20) NOT NULL ENABLE
)
/
INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('1', '1','5', '1', '1011')
/
INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('2', '1','10', '2', '1012')
/
INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('3', '1','20', '3', '1013')
/
INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('4', '1','50', '5', '1014')
/
INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('5', '1','60', '7', '1015')
/
INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('6', '1','100', '7', '1016')
/
INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('7', '1','200', '15', '1017')
/
INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('8', '1','250', '15', '1018')
/
INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('9', '1','500', '30', '1019')
/
INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('10', '1','750', '30', '1020')
/
INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('11', '1','1024', '30', '1021')
/
INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('12', '1','2048', '30', '1022')
/

INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('13', '1','3072', '30', '1023')
/
INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('14', '1','5120', '60', '1024')
/
INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('15', '1','10240', '60', '1025')
/
INSERT INTO NEW_PROVISIONING_PACKAGES (ID, PACKAGE_CATEGORY_ID,VOLUME,VALIDITY,OFFER_ID)
VALUES('16', '1','30720', '30', '1026')
/




