CREATE TABLE SERVICE_DATA_PROVISIONED
   ( ID VARCHAR2(20), 
    MSISDN VARCHAR2(20), 
    PROVISIONED_AT TIMESTAMP (6), 
    DATA_BEFORE VARCHAR2(20), 
    DATA_AFTER VARCHAR2(20), 
    PACKAGE_ID VARCHAR2(20), 
    PACKAGE_NAME VARCHAR2(40), 
    EXPIRES_AT TIMESTAMP (6), 
    TRANSACTION_ID VARCHAR2(20)
   )
/
 
CREATE SEQUENCE SERVICE_DATA_PROVISIONED_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE
/

CREATE OR REPLACE TRIGGER SERVICE_DATA_PROVISIONED_TRG BEFORE INSERT ON SERVICE_DATA_PROVISIONED 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT SERVICE_DATA_PROVISIONED_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL
/
    END IF
/
  END COLUMN_SEQUENCES
/
END
/
ALTER TRIGGER SERVICE_DATA_PROVISIONED_TRG ENABLE
/
 
