CREATE TABLE USER_PROFILES
   (    "ID" NUMBER NOT NULL ENABLE,
    "ALLOWED_PACKAGE_IDS" VARCHAR2(100),
    "CREATED_AT" TIMESTAMP (6),
    "MODIFIED_AT" TIMESTAMP (6),
    "NAME" VARCHAR2(100) NOT NULL ENABLE,
    "PASSWORD" VARCHAR2(30) NOT NULL ENABLE,
     CONSTRAINT "USER_PROFILES_PK" PRIMARY KEY ("ID")
)

/
