CREATE SEQUENCE "SERVICES_SEQ"  MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE SEQUENCE "SERVICE_EVENTS_SEQ" MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE SEQUENCE "SERVICE_PACKAGES_SEQ" MINVALUE 1 NOMAXVALUE  INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
