CREATE TABLE "SERVICES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"CREATED_AT" TIMESTAMP (6), 
	"UPDATED_AT" TIMESTAMP (6)
   );

CREATE TABLE "SERVICE_PACKAGES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"SERVICE_ID" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"CREATED_AT" TIMESTAMP (6), 
	"MODIFIED_AT" TIMESTAMP (6)
   );

CREATE TABLE "SERVICE_EVENTS"
    (   "ID" NUMBER,
        "MSISDN" VARCHAR2(20),
        "SERVICE_ID" VARCHAR2(20),
        "EXECUTE_AT" TIMESTAMP (6),
        "STATUS" VARCHAR2(20),
        "EVENT_ID" VARCHAR2(20),
        "PARAMETERS" VARCHAR2(200),
        "CAN_EXECUTE" NUMBER,
        CONSTRAINT ID_SEREVENTS_PK PRIMARY KEY(ID))
        PARTITION BY RANGE (EXECUTE_AT)
        INTERVAL (NUMTOYMINTERVAL(2,'MONTH')) 
        (
        PARTITION SEREVENTS_P1 VALUES LESS THAN (TO_DATE('Start_date','DD-MM-YYYY')),
        PARTITION SEREVENTS_P2 VALUES LESS THAN (TO_DATE('','DD-MM-YYYY')),
        PARTITION SEREVENTS_P3 VALUES LESS THAN (TO_DATE('','DD-MM-YYYY')),
        PARTITION SEREVENTS_P4 VALUES LESS THAN (TO_DATE('','DD-MM-YYYY')),
        PARTITION SEREVENTS_P5 VALUES LESS THAN (TO_DATE('','DD-MM-YYYY')),
        PARTITION SEREVENTS_P6 VALUES LESS THAN (TO_DATE('','DD-MM-YYYY')),
        PARTITION SEREVENTS_P7 VALUES LESS THAN (TO_DATE('','DD-MM-YYYY')),
        PARTITION SEREVENTS_P8 VALUES LESS THAN (TO_DATE('','DD-MM-YYYY')),
        PARTITION SEREVENTS_P9 VALUES LESS THAN (TO_DATE('','DD-MM-YYYY')),
        PARTITION SEREVENTS_P10 VALUES LESS THAN (TO_DATE('','DD-MM-YYYY')),
        PARTITION SEREVENTS_P11 VALUES LESS THAN (TO_DATE('','DD-MM-YYYY')),
        PARTITION SEREVENTS_P12 VALUES LESS THAN (TO_DATE('','DD-MM-YYYY')))
/
