CREATE OR REPLACE TRIGGER "SERVICES_TRG" BEFORE INSERT ON SERVICES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT SERVICES_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

ALTER TRIGGER "SERVICES_TRG" ENABLE;


CREATE OR REPLACE TRIGGER "SERVICE_EVENTS_TRG" BEFORE INSERT ON SERVICE_EVENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT SERVICE_EVENTS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

ALTER TRIGGER "SERVICE_EVENTS_TRG" ENABLE;


CREATE OR REPLACE TRIGGER "SERVICE_PACKAGES_TRG" BEFORE INSERT ON SERVICE_PACKAGES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT SERVICE_PACKAGES_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

ALTER TRIGGER "SERVICE_PACKAGES_TRG" ENABLE;



