CREATE TABLE ME2U (ID NUMBER NOT NULL ENABLE,
MSISDN VARCHAR2(15) NOT NULL ENABLE,
RECIPIENT VARCHAR2(15) NOT NULL ENABLE,
BAL_BEFORE VARCHAR2(15),
BAL_AFTER VARCHAR2(15),
REC_BAL_BEFORE VARCHAR2(15),
REC_BAL_AFTER VARCHAR2(15),
REC_EXPIRY TIMESTAMP (6),
STATUS NUMBER(2) NOT NULL ENABLE,
AMOUNT NUMBER(20) NOT NULL ENABLE,
CREATED_AT TIMESTAMP (6),
CONSTRAINT ME2U_PK PRIMARY KEY (ID))
PARTITION BY RANGE (CREATED_AT)
INTERVAL (NUMTOYMINTERVAL(2,'MONTH'))
(
PARTITION SEREVENTS_P1 VALUES LESS THAN (TO_DATE('1-10-2013','DD-MM-YYYY')),
PARTITION SEREVENTS_P2 VALUES LESS THAN (TO_DATE('1-12-2013','DD-MM-YYYY')),
PARTITION SEREVENTS_P3 VALUES LESS THAN (TO_DATE('1-02-2014','DD-MM-YYYY')),
PARTITION SEREVENTS_P4 VALUES LESS THAN (TO_DATE('1-04-2014','DD-MM-YYYY')),
PARTITION SEREVENTS_P5 VALUES LESS THAN (TO_DATE('1-06-2014','DD-MM-YYYY')),
PARTITION SEREVENTS_P6 VALUES LESS THAN (TO_DATE('1-08-2014','DD-MM-YYYY')),
PARTITION SEREVENTS_P7 VALUES LESS THAN (TO_DATE('1-10-2014','DD-MM-YYYY')),
PARTITION SEREVENTS_P8 VALUES LESS THAN (TO_DATE('1-12-2014','DD-MM-YYYY')),
PARTITION SEREVENTS_P9 VALUES LESS THAN (TO_DATE('1-02-2015','DD-MM-YYYY')),
PARTITION SEREVENTS_P10 VALUES LESS THAN (TO_DATE('1-04-2015','DD-MM-YYYY')),
PARTITION SEREVENTS_P11 VALUES LESS THAN (TO_DATE('1-06-2015','DD-MM-YYYY')),
PARTITION SEREVENTS_P12 VALUES LESS THAN (TO_DATE('1-08-2015','DD-MM-YYYY')))
/
