CREATE TABLE BUNDLE_RESPONSES(
ID NUMBER NOT NULL,
REQUEST_ID NUMBER(11,0),
MSISDN VARCHAR2(15),
RESPONSE VARCHAR2(300),
ACTION NUMBER(1,0),
CREATED_AT TIMESTAMP (6),
CONSTRAINT BUNDLE_RESP_PK PRIMARY KEY(ID)
)

/
create sequence RESPONSE_REQ_SQC MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 ORDER NOCYCLE;
/

CREATE OR REPLACE TRIGGER "RESPONSE_REQ_TRG" BEFORE INSERT ON BUNDLE_RESPONSES 
FOR EACH ROW 
BEGIN
<<COLUMN_SEQUENCES>>
BEGIN
IF :NEW.ID IS NULL THEN
SELECT RESPONSE_REQ_SQC.NEXTVAL INTO :NEW.ID FROM DUAL;
END IF;
END COLUMN_SEQUENCES;
END;
