CREATE OR REPLACE TRIGGER "RESPONSE_REQ_TRG" BEFORE INSERT ON BUNDLE_RESPONSES 
FOR EACH ROW 
BEGIN
<<COLUMN_SEQUENCES>>
BEGIN
IF :NEW.ID IS NULL THEN
SELECT RESPONSE_REQ_SQC.NEXTVAL INTO :NEW.ID FROM DUAL
/
END IF
/
END COLUMN_SEQUENCES
/
END
/
