CREATE TABLE ME2U_CDR
(
ID NUMBER(20),
MSISDN VARCHAR2(15),
RECIPIENT VARCHAR2(15),
AMOUNT VARCHAR2(15),
CREATED_AT TIMESTAMP,
UPDATED_AT TIMESTAMP,
BAL_BEFORE VARCHAR2(15),
BAL_AFTER VARCHAR2(15),
REC_BAL_BEFORE VARCHAR2(15),
REC_BAL_AFTER VARCHAR2(15),
STATUS_CODE NUMBER(5),
CONSTRAINT ME2U_CDR_PK PRIMARY KEY (ID)
);
/

CREATE SEQUENCE ME2U_CDR_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE CACHE 20 NOCYCLE;
