CREATE TABLE "GOODMORNING_CDRS"
    (   "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" VARCHAR2(12) NOT NULL ENABLE,
        "ACTION" VARCHAR2(10) NOT NULL ENABLE,
        "STATUS" NUMBER(2) NOT NULL ENABLE,
        "CREATED_AT" TIMESTAMP (6),
        CONSTRAINT GMG_PK PRIMARY KEY(ID)
    )
/
