CREATE TABLE "GOODMORNING_WHITELIST"
    (   "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" VARCHAR2(12) UNIQUE,
        "CREATED_AT" TIMESTAMP (6),
        CONSTRAINT GMM_WL_PK PRIMARY KEY(ID)
    )
/
